### ISSUE TITLE
Standardize required dataset metadata

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#1]
We need to establish which metadata should be included/tracked/recorded for our initial pipeline.

This is analogous to [`/etc`](https://bitbucket.org/lwaldron/curatedovariandata/src/12a1df4cd442/etc/?at=default) in the [curatedOvarianData source](https://bitbucket.org/lwaldron/curatedovariandata).

<details><summary>Metadata tracked by curatedOvarianData</summary>

**Datasets**

- accession
- pubMedIds
- platform_title
- citation
- name
- platform_shorttitle
- platform_summary
- platform_manufacturer
- platform_distribution
- platform_accession
- platform_technology
- year
- title
- warnings

**Platforms**

- Accession ID
- GEO_platform_accession
- platform_summary
- biomart_ID
</details><br>

Building off lists prepared by @tgerke, Dr. Costello, Svitlana, and @jhcreed, I've started the following list:

- label
- title
- year
- accession
- pubmed_id (multiple values allowed)
- citation
- doi
- size
    - n
    - comments
- platform (may contain multiple entries with the following)
    - name
    - summary
    - manufacturer
    - distribution
    - accession
    - technology
- link (may include any of the following)
    - pub
    - data
    - website
    - primary (default: website, pub, data)
- comments

The goal is to store this as [YAML](https://learnxinyminutes.com/docs/yaml/), for example:

```yaml
label: Lapointe, Pollack 2004
title: Gene expression profiling identifies clinically relevant subtypes of prostate cancer
year: 2004
accession: GSE3933
pubmed_id: [14711987]
doi: 10.1073/pnas.0304146101
platform:
  - name: SHBB
    manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
    distribution: non-commercial
    accession: GPL2695
    technology: spotted DNA/cDNA
  - name: SHCQ
    manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
    distribution: non-commercial
    accession: GPL3044
    technology: spotted DNA/cDNA
  - name: SHBW
    manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
    distribution: non-commercial
    accession: GPL3289
    technology: spotted DNA/cDNA
citation: >
  Lapointe J, Li C, Higgins JP, van de Rijn M et al. 
  Gene expression profiling identifies clinically relevant subtypes of prostate cancer. 
  Proc Natl Acad Sci U S A 2004 Jan 20;101(3):811-6.
size:
  n: 62
  comments: n=62 primary, n=42 normal, n=9 lymph
link: 
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE3933
```

Are there fields or metadata missing from this list?
