### ISSUE TITLE
Data - GSE3325 - Varambally, Chinnaiyan 2005

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#10]
Source: GEO
 
```yaml
label: Varambally, Chinnaiyan 2005
accession: GSE3325
pubmed_id: 16286247
platform:
- name: HG-U133_Plus_2
  manufacturer: Affymetrix
  distribution: "commercial\t"
  accession: "GPL570\t"
  technology: in situ oligonucleotide
citation: Varambally S, Yu J, Laxman B, Rhodes DR et al. Integrative genomic and proteomic
  analysis of prostate cancer reveals signatures of metastatic progression. Cancer
  Cell 2005 Nov;8(5):393-406.
size:
  'n': 19
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE3325

```
