### ISSUE TITLE
Data - GSE5377 - Stoss, Albers 2008

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#11]
Source: GEO
 
```yaml
label: Stoss, Albers 2008
accession: GSE5377
pubmed_id: 17646850
platform:
- name: '[HG-Focus] Affymetrix Human HG-Focus Target Array'
  manufacturer: Affymetrix
  distribution: "commercial\t"
  accession: GSE5377
  technology: in situ oligonucleotide
citation: Stoss O, Werther M, Zielinski D, Middel P et al. Transcriptional profiling
  of transurethral resection samples provides insight into molecular mechanisms of
  hormone refractory prostate cancer. Prostate Cancer Prostatic Dis 2008;11(2):166-72.

```
