### ISSUE TITLE
Data - GSE6919 - GSE6919

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#13]
Source: GEO
 
```yaml
label: GSE6919
accession: GSE6919
pubmed_id:
- 17430594
- 15254046
- 15892885
- 17071602
platform:
- name: '[HG_U95B] Affymetrix Human Genome U95B Array'
  manufacturer: Affymetrix
  distribution: "commercial\t"
  accession: GPL92
  technology: in situ oligonucleotide
- name: '[HG_U95C] Affymetrix Human Genome U95C Array'
  manufacturer: Affymetrix
  distribution: "commercial\t"
  accession: GPL93
  technology: in situ oligonucleotide
- name: '[[HG_U95Av2] Affymetrix Human Genome U95 Version 2 Array'
  manufacturer: Affymetrix
  distribution: "commercial\t"
  accession: GPL8300
  technology: in situ oligonucleotide

```
