### ISSUE TITLE
Data - GSE6956 - Wallace, Ambs 2008

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#14]
Source: GEO
 
```yaml
label: Wallace, Ambs 2008
accession: GSE6956
pubmed_id: 18245496
platform:
- name: '[HG-U133A_2] Affymetrix Human Genome U133A 2.0 Array'
  manufacturer: Affymetrix
  distribution: "commercial\t"
  accession: GPL571
  technology: in situ oligonucleotide
citation: Wallace TA, Prueitt RL, Yi M, Howe TM et al. Tumor immunobiological differences
  in prostate cancer between African-American and European-American men. Cancer Res
  2008 Feb 1;68(3):927-36.

```
