### ISSUE TITLE
Data - GSE7055 - Prueitt, Ambs 2008

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#15]
Source: GEO
 
```yaml
label: Prueitt, Ambs 2008
accession: GSE7055
pubmed_id: 18459106
platform:
- name: '[HG-U133A_2] Affymetrix Human Genome U133A 2.0 Array'
  manufacturer: Affymetrix
  distribution: "commercial\t"
  accession: GPL571
  technology: in situ oligonucleotide
citation: Prueitt RL, Yi M, Hudson RS, Wallace TA et al. Expression of microRNAs and
  protein-coding genes associated with perineural invasion in prostate cancer. Prostate
  2008 Aug 1;68(11):1152-64.

```
