### ISSUE TITLE
Data - GSE7949 - GSE7949

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#16]
Source: GEO
 
```yaml
label: GSE7949
accession: GSE7949
platform:
- name: University of Pennsylvania/Nathanson Lab_HomoSapiens_ChromosomeRegion_Virtual
  manufacturer: Weber Laboratory/School of Medicine/University of Pennsylvania
  distribution: virtual
  accession: GPL5338
  technology: other
title: 'Prostate Adenocarcinoma: Candidate Genomic Signatures Prognostic of Biochemical
  Failure'
year: '2007'

```
