### ISSUE TITLE
Data - GSE8511 - Poisson, Chinnaiyan 2011

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#17]
Source: GEO
 
```yaml
label: Poisson, Chinnaiyan 2011
accession: GSE8511
platform:
- name: Agilent-012391 Whole Human Genome Oligo Microarray G4112A (Feature Number
    version)
  manufacturer: Agilent
  distribution: "commercial\t"
  accession: GPL1708
  technology: in situ oligonucleotide
title: Profiling of prostate tissues in prostate cancer progression
year: '2011'

```
