### ISSUE TITLE
Data - GSE9347 - Arencibia, Bonnin 2009

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#18]
Source: GEO
 
```yaml
label: Arencibia, Bonnin 2009
accession: GSE9347
pubmed_id: 19148481
platform:
- name: CNIO H. sapiens 13.6k Oncochip 1
  distribution: "non-commercial\t"
  accession: GPL1998
  technology: spotted DNA/cDNA
citation: Arencibia JM, Martên S, P_rez-Rodrêguez FJ, Bonnin A. Gene expression profiling
  reveals overexpression of TSPAN13 in prostate cancer. Int J Oncol 2009 Feb;34(2):457-63.

```
