### ISSUE TITLE
Data - GSE10645 - Nakagawa, Jenkins 2008

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#19]
Source: GEO
 
```yaml
label: Nakagawa, Jenkins 2008
accession: GSE10645
pubmed_id: 18846227
platform:
- name: DASL Human Cancer Panel by Gene
  manufacturer: Illumina
  distribution: commercial
  accession: GPL5858
  technology: oligonucleotide beads
- name: DASL Human Cancer Panel by Gene
  manufacturer: Illumina
  distribution: commercial
  accession: GPL5873
  technology: oligonucleotide beads
citation: Nakagawa T, Kollmeyer TM, Morlan BW, Anderson SK et al. A tissue biomarker
  panel predicting systemic progression after PSA recurrence post-definitive prostate
  cancer therapy. PLoS One 2008;3(5):e2318.

```
