### ISSUE TITLE
Data - GSE6752 - Chandran, Monzon 2007

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#2]
Source: GEO
 
```yaml
label: Chandran, Monzon 2007
accession: GSE6752
pubmed_id: 17430594
platform:
- name: GE Healthcare/Amersham Biosciences CodeLink UniSet Human 20K I Bioarray
  manufacturer: GE Healthcare
  distribution: commercial
  accession: GPL2891
  technology: spotted oligonucleotide
citation: Chandran UR, Ma C, Dhir R, Bisceglia M et al. Gene expression profiles of
  prostate cancer reveal involvement of multiple molecular pathways in the metastatic
  process. BMC Cancer 2007 Apr 12;7:64.
size:
  'n': 24
  comments: n=24 samples from 4 patients (multiple metastatic samples)
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE6752

```
