### ISSUE TITLE
Data - GSE14206 - GSE14206

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#20]
Source: GEO
 
```yaml
label: GSE14206
accession: GSE14206
pubmed_id:
- 20479932
- 21266046
platform:
- name: Agilent-012097 Human 1A Microarray (V2) G4110B (Feature Number version)
  manufacturer: Agilent
  distribution: commercial
  accession: GPL887
  technology: in situ oligonucleotide

```
