### ISSUE TITLE
Data - GSE16560 - Sboner, Andr_n 2010

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#21]
Source: GEO
 
```yaml
label: Sboner, Andr_n 2010
accession: GSE16560
pubmed_id: 20233430
platform:
- name: "Human 6k Transcriptionally Informative Gene Panel for DASL\t"
  manufacturer: Illumina
  distribution: commercial
  accession: GPL5474
  technology: oligonucleotide beads
citation: >
  Sboner A, Demichelis F, Calza S, Pawitan Y et al. 
  Molecular sampling of prostate cancer: a dilemma for predicting disease progression. 
  BMC Med Genomics 2010 Mar 16;3:8."
```
