### ISSUE TITLE
Data - GSE21032 - Taylor, Gerald 2010

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#22]
Source: GEO
 
```yaml
label: Taylor, Gerald 2010
accession: GSE21032
pubmed_id: 20579941
platform:
- name: '[HuEx-1_0-st] Affymetrix Human Exon 1.0 ST Array [probe set (exon) version]'
  manufacturer: Affymetrix
  distribution: commercial
  accession: GPL5188
  technology: in situ oligonucleotide
citation: Taylor BS, Schultz N, Hieronymus H, Gopalan A et al. Integrative genomic
  profiling of human prostate cancer. Cancer Cell 2010 Jul 13;18(1):11-22.

```
