### ISSUE TITLE
Data - GSE25136 - Sun, Goodison 2009

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#23]
Source: GEO
 
```yaml
label: Sun, Goodison 2009
accession: GSE25136
pubmed_id: 19343730
platform:
- name: '[HG-U133A] Affymetrix Human Genome U133A Array'
  manufacturer: Affymetrix
  distribution: commercial
  accession: GPL96
  technology: in situ oligonucleotide
citation: Sun Y, Goodison S. Optimizing molecular signatures for predicting prostate
  cancer recurrence. Prostate 2009 Jul 1;69(10):1119-27.

```
