### ISSUE TITLE
Data - GSE2109 - expO, IGC 2005

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#24]
Source: GEO
 
```yaml
label: expO, IGC 2005
accession: GSE2109
platform:
- name: '[HG-U133_Plus_2] Affymetrix Human Genome U133 Plus 2.0 Array'
  manufacturer: Affymetrix
  distribution: commercial
  accession: GPL570
  technology: in situ oligonucleotide
citation: EXpression Project for Oncology, International Genomics Consortium, www.intgen.org
size:
  'n': 60
  comments: n=60 after subsetting to prostate
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE2109

```
