### ISSUE TITLE
Data - Liu P, Moreno CS 2006

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#25]
Source: Unknown
 
```yaml
label: Liu P, Moreno CS 2006
title: >
  Sex-Determining Region Y Box 4 Is a Transforming Oncogene in 
  Human Prostate Cancer Cells
pubmed_id: 16618720
doi: 10.1158/0008-5472.CAN-05-3055
platform:
- name: '[HG-U133A] Affymetrix Human Genome U133A Array'
  manufacturer: Affymetrix
  distribution: commercial
  accession: GPL96
  technology: in situ oligonucleotide
- name: '[HG-U133A] Affymetrix Human Genome U133B Array'
  manufacturer: Affymetrix
  distribution: commercial
  accession: GPL97
  technology: in situ oligonucleotide
citation: > 
  Liu P, Ramachandran S, Ali Seyed M, Scharer CD, Laycock N, Dalton WB, Williams
  H, Karanam S, Datta MW, Jaye DL, Moreno CS Cancer Res. 2006 Apr 15;66(8):4011-9
link:
  pub: http://cancerres.aacrjournals.org/content/66/8/4011
```
