### ISSUE TITLE
Data - GSE79021 - Sinnott 2017

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#26]
Source: GEO
 
```yaml
label: GSE79021
title: >
  Gene expression profiling of human prostate tumors identifies chromatin 
  remodeling as a molecular link between obesity and lethal prostate cancer
accession: GSE79021
pubmed_id: [27663590]
doi: 10.1158/1078-0432.CCR-16-1245
year: 2017
platform:
  - name: Affymetrix Human Gene 1.0 ST Array [Gene Symbols]
    manufacturer: Affymetrix
    distribution: custom-commercial
    accession: GPL19370
    technology: in situ oligonucleotide
citation: >
  Sinnott JA, Peisch SF, Tyekucheva S, et al. 
  Prognostic Utility of a New mRNA Expression Signature of Gleason Score. 
  Clin Cancer Res. 2017;23(1):81-87.
size:
  'n': 602
  comments: >
    Gene expression profiling was performed on 602 prostate tissue samples 
    (402 tumor and 200 normal) from the Health Professionals Follow-up Study 
    and Physicians' Health Study Prostate Tumor Cohort. This study includes 
    analysis of 400 samples in GSE62872.
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE79021
  pub: https://www.ncbi.nlm.nih.gov/pubmed/27663590
```
