### ISSUE TITLE
Data - GSE62872 - Penney 2014

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#27]
Source: GEO
 
```yaml
label: GSE62872
title: >
  Association of Prostate Cancer Risk Variants with Gene Expression 
  in Normal and Tumor Tissue
accession: GSE62872
pubmed_id: [25371445]
doi: 10.1158/1055-9965.EPI-14-0694-T
year: 2014
platform:
  - name: Affymetrix Human Gene 1.0 ST Array [Gene Symbols]
    manufacturer: Affymetrix
    distribution: custom-commercial
    accession: GPL19370
    technology: in situ oligonucleotide
citation: >
  Penney KL, Sinnott JA, Tyekucheva S, et al. 
  Association of prostate cancer risk variants with gene expression in normal and tumor tissue. 
  Cancer Epidemiol Biomarkers Prev. 2015;24(1):255-60.
size:
  'n': 424
  comments: >
    264 prostate tumor and 160 normal prostate tissue samples from the Health 
    Professionals Follow-up Study and Physicians' Health Study Prostate Tumor Cohort.
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE62872
  pub: http://cebp.aacrjournals.org/content/24/1/255
```
