### ISSUE TITLE
Data - GSE40272 - Gulzar, Mckenney, Brooks 2012

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#28]
Source: GEO
 
```yaml
label: GSE40272
title: Increased expression of NuSAP in recurrent prostate cancer is mediated by E2F1
accession: GSE40272
year: 2012
pubmed_id: [22349817]
doi: 10.1038/onc.2012.27
platform:
  - accession: GPL9497
    name: SMD Print_1529 Homo sapiens
    manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
    distribution: non-commercial
    technology: spotted DNA/cDNA
  - accession: GPL15971
    name: SMD Print_1392 hos Homo sapiens
    manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
    distribution: non-commercial
    technology: spotted DNA/cDNA
  - accession: GPL15972
    name: SMD Print_1540 hoaf Homo sapiens
    manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
    distribution: non-commercial
    technology: spotted DNA/cDNA
citation: >
  Gulzar ZG, Mckenney JK, Brooks JD. 
  Increased expression of NuSAP in recurrent prostate cancer is mediated by E2F1. 
  Oncogene. 2013;32(1):70-7.
size:
  'n': 98
  comments: 98 prostate tumors and 52 benign adjacent prostate tissue samples with detailed clinical annotation
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE40272
  pub: https://www.nature.com/articles/onc201227
```
