### ISSUE TITLE
Data - GSE70770 - Ross-Adams et al. 2015

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#29]
Source: GEO
 
```yaml
label: GSE70770
title: Prostate cancer stratification using molecular profiles
accession: GSE70770
year: 2015
pubmed_id: [26501111, 26950096]
doi: 10.1016/j.ebiom.2015.07.017
platform:
  - accession: GPL6801
    name: '[GenomeWideSNP_6] Affymetrix Genome-Wide Human SNP 6.0 Array'
    manufacturer: Affymetrix
    distribution: commercial
    technology: in situ oligonucleotide
  - accession: GPL10558
    name: Illumina HumanHT-12 V4.0 expression beadchip
    manufacturer: Illumina Inc.
    distribution: commercial
    technology: oligonucleotide beads
  - accession: GPL16104
    name: Illumina HumanOmni2.5-8 BeadChip
    manufacturer: Illumina, Inc.
    distribution: custom-commercial
    technology: oligonucleotide beads
  - accession: GPL20641
    name: Illumina HumanOmni2.5M-8v1-1_B [data table]
    manufacturer: Illumina
    distribution: commercial
    technology: oligonucleotide beads
citation: >
  Ross-Adams H, Lamb AD, Dunning MJ, et al. 
  Integration of copy number and transcriptomics provides risk stratification 
  in prostate cancer: A discovery and validation cohort study. 
  EBioMedicine. 2015;2(9):1133-44.
size:
  'n': 808
  comments: > 
    Ross-Adams (2105): 482 tumour, benign and germline samples from 259 men 
    with primary prostate cancer. Whitington (2016): 295 prostate cancer chromatin
    immunoprecipitation and sequencing experiments with genotype and gene 
    expression data from 602 prostate tumor samples. GEO page: 808 samples.
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE70770
  pub: https://www.sciencedirect.com/science/article/pii/S2352396415300712
comments: Superset, includes GSE70768, GSE70769, GSE1965
```
