### ISSUE TITLE
Data - GSE18655 - Barwick, Abramovitz 2010

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#3]
Source: GEO
 
```yaml
label: Barwick, Abramovitz 2010
accession: GSE18655
pubmed_id: 20068566
platform:
- name: DASL Human Cancer Panel by Gene
  manufacturer: Illumina
  distribution: commercial
  accession: GPL5858
  technology: oligonucleotide beads
citation: Barwick BG, Abramovitz M, Kodani M, Moreno CS et al. Prostate cancer genes
  associated with TMPRSS2-ERG gene fusion and prognostic of biochemical recurrence
  in multiple cohorts. Br J Cancer 2010 Feb 2;102(3):570-6.
size:
  'n': 139
  comments: n=139, DASL=502 genes
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE18655

```
