### ISSUE TITLE
Data - GSE26367

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#30]
Source: GEO
 
```yaml
label: GSE26367
title: Protein-coding and MicroRNA Biomarkers of Recurrence of Prostate Cancer Following Radical Prostatectomy
accession: GSE26367
year: 2011
pubmed: 21703393
doi: 10.1016/j.ajpath.2011.03.008
platform:
  - accession: GPL11309
    name: Illumina Custom Prostate Cancer DASL Panel 1.5K expression beadchip
    manufacturer: Illumina Inc.
    distribution: custom-commercial
    technology: oligonucleotide beads
  - accession: GPL11350
    name: Illumina Custom Prostate Cancer DASL Panel miRNA
    manufacturer: Illumina Inc.
    distribution: custom-commercial
    technology: oligonucleotide beads
citation: >
  Long Q, Johnson BA, Osunkoya AO, et al. 
  Protein-coding and microRNA biomarkers of recurrence of prostate cancer following radical prostatectomy. 
  Am J Pathol. 2011;179(1):46-54.
size:
  'n': 70
  comments: 70 formalin-fixed, paraffin-embedded radical prostatectomy specimens with known long-term outcomes
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE26367
  pub: https://www.sciencedirect.com/science/article/pii/S000294401100321X
comment: Superseries, includes GSE26022, GSE26242, GSE26245
```
