### ISSUE TITLE
Data - GSE51066 - Ross et al. 2016

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#31]
Source: GEO
 
```yaml
label: GSE51066
title: A genomic classifier predicting metastatic disease progression in men with biochemical recurrence after prostatectomy
accession: GSE51066
year: 2016
pubmed_id: [24145624]
doi: 10.1038/pcan.2013.49
platform:
  - accession: GPL5188
    name: '[HuEx-1_0-st] Affymetrix Human Exon 1.0 ST Array [probe set (exon) version]'
    manufacturer: Affymetrix
    distribution: commercial
    technology: in situ oligonucleotide
citation: >
  Ross AE, Feng FY, Ghadessi M, et al. 
  A genomic classifier predicting metastatic disease progression in men with 
  biochemical recurrence after prostatectomy. 
  Prostate Cancer Prostatic Dis. 2014;17(1):64-9.
size:
  'n': 85
  comments: 85 clinically high-risk patients who developed biochemical recurrence after radical prostatectomy
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE51066
  pub: https://www.nature.com/articles/pcan201349
```
