### ISSUE TITLE
Data - GSE62116 - GenomeDx

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#32]
Source: GEO
 
```yaml
label: GSE62116
title: Validation of a genomic classifier that predicts metastasis following radical prostatectomy in at risk patient population
accession: GSE62116
year: 2014
pubmed_id: [23770138, 26246306, 26631616]
doi: 10.1016/j.juro.2013.06.017
platform:
  - accession: GPL5188
    name: '[HuEx-1_0-st] Affymetrix Human Exon 1.0 ST Array [probe set (exon) version]'
    manufacturer: Affymetrix
    distribution: commercial
    technology: in situ oligonucleotide
citation: >
  Karnes RJ, Bergstralh EJ, Davicioni E, et al. 
  Validation of a genomic classifier that predicts metastasis following radical 
  prostatectomy in an at risk patient population. 
  J Urol. 2013;190(6):2047-53.
size:
  'n': 235
  comments: We generated 22-marker genomic classifier scores for 235 patients with available genomic data.
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE62116
  pub: https://www.sciencedirect.com/science/article/pii/S002253471304603X
```
