### ISSUE TITLE
Data - TCGA, Cell 2015

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#33]
Source: cBioportal
 
```yaml
label: TCGA, Cell 2015
pubmed_id: 26544944
doi: 10.1016/j.cell.2015.10.025
size:
  'n': 333
platform:
- technology: RNAseq
link:
  primary: http://www.cbioportal.org/study?id=prad_tcga_pub#summary
  data: http://download.cbioportal.org/prad_tcga_pub.tar.gz

```
