### ISSUE TITLE
Data - SU2C/PCF Dream Team, Cell 2015

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#34]
Source: cBioportal
 
```yaml
label: SU2C/PCF Dream Team, Cell 2015
pubmed_id: 26000489
size:
  'n': 118
platform:
- technology: RNAseq
link:
  primary: http://www.cbioportal.org/study?id=prad_su2c_2015#summary
  data: http://download.cbioportal.org/prad_su2c_2015.tar.gz

```
