### ISSUE TITLE
Data - PRAD Broad, Cell 2013

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#35]
Source: cBioportal
 
```yaml
label: PRAD Broad, Cell 2013
pubmed_id: 23622249
size:
  'n': 16
platform:
- technology: microarray
link:
  primary: http://www.cbioportal.org/study?id=prad_broad_2013#summary
  data: http://download.cbioportal.org/prad_broad_2013.tar.gz

```
