### ISSUE TITLE
Data - PRAD Broad, Nat Gen 2012

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#36]
Source: cBioportal
 
```yaml
label: PRAD Broad, Nat Gen 2012
pubmed_id: 22610119
size:
  'n': 31
platform:
- technology: microarray
link:
  primary: http://www.cbioportal.org/study?id=prad_broad#summary
  data: http://download.cbioportal.org/prad_broad.tar.gz
comments: overlaps with PRAD Broad Cell 2013?

```
