### ISSUE TITLE
Data - PRAD FHCRC, Nat Med 2016

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#37]
Source: cBioportal
 
```yaml
label: PRAD FHCRC, Nat Med 2016
pumed_id: 26928463
size:
  'n': 171
platform:
- technology: microarray
link:
  primary: http://www.cbioportal.org/study?id=prad_fhcrc#summary
  data: http://download.cbioportal.org/prad_fhcrc.tar.gz

```
