### ISSUE TITLE
Data - PRAD MICH, Nature 2012

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#38]
Source: cBioportal
 
```yaml
label: PRAD MICH, Nature 2012
pubmed_id: 22722839
size:
  'n': 10
platform:
- technology: RNAseq
link:
  primary: http://www.cbioportal.org/study?id=prad_mich#summary
  data: http://download.cbioportal.org/prad_mich.tar.gz

```
