### ISSUE TITLE
Data - Liu et al. 2006

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#39]
Source: ArrayExpress
 
```yaml
label: Liu et al. 2006
pubmed_id: 16618720
size:
  'n': 57
platform:
- name: Affy U133
link:
  primary: https://www.ebi.ac.uk/arrayexpress/experiments/E-TABM-26/

```
