### ISSUE TITLE
Data - GSE2443 - Best, Chuaqui 2005

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#4]
Source: GEO
 
```yaml
label: Best, Chuaqui 2005
accession: GSE2443
pubmed_id: 16203770
platform:
- name: HG-U133A
  manufacturer: Affymetrix
  distribution: commercial
  accession: GPL96
  technology: in situ oligonucleotide
citation: Best CJ, Gillespie JW, Yi Y, Chandramouli GV et al. Molecular alterations
  in primary prostate cancer after androgen ablation therapy. Clin Cancer Res 2005
  Oct 1;11(19 Pt 1):6823-34.
size:
  'n': 20
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE2443

```
