### ISSUE TITLE
Data - Kamoun et al.

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#40]
Source: ArrayExpress
 
```yaml
label: Kamoun et al.
pubmed_id: 29945238
size:
  'n': 132
link:
  primary: https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-6131/

```
