### ISSUE TITLE
Data - GSE3933 - Lapointe, Pollack 2004

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#5]
Source: GEO
 
```yaml
label: Lapointe, Pollack 2004
accession: GSE3933
pubmed_id: 14711987
doi: 10.1073/pnas.0304146101
platform:
- name: SHBB
  manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
  distribution: non-commercial
  accession: GPL2695
  technology: spotted DNA/cDNA
- name: SHCQ
  manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
  distribution: non-commercial
  accession: GPL3044
  technology: spotted DNA/cDNA
- name: SHBW
  manufacturer: Stanford Functional Genomics Facility, Stanford School of Medicine
  distribution: non-commercial
  accession: GPL3289
  technology: spotted DNA/cDNA
citation: |
  Lapointe J, Li C, Higgins JP, van de Rijn M et al. Gene expression profiling identifies clinically relevant subtypes of prostate cancer. Proc Natl Acad Sci U S A 2004 Jan 20;101(3):811-6.
size:
  'n': 62
  comments: n=62 primary, n=42 normal, n=9 lymph
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE3933

```
