### ISSUE TITLE
Data - GSE8402 - Setlur, Rubin 2008

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#6]
Source: GEO
 
```yaml
label: Setlur, Rubin 2008
accession: GSE8402
pubmed_id: 18505969
platform:
- name: Human 6k Transcriptionally Informative Gene Panel for DASL
  manufacturer: Illumina
  distribution: commercial
  accession: "GPL5474\t"
  technology: "oligonucleotide beads\t"
citation: Setlur SR, Mertz KD, Hoshida Y, Demichelis F et al. Estrogen-dependent signaling
  in a molecularly distinct subclass of aggressive prostate cancer. J Natl Cancer
  Inst 2008 Jun 4;100(11):815-25.
size:
  'n': 472
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE8402

```
