### ISSUE TITLE
Data - GSE6811 - Tamura, Nakagawa 2007

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#7]
Source: GEO
 
```yaml
label: Tamura, Nakagawa 2007
accession: GSE6811
pubmed_id: 17545589
platform:
- name: YN Human 36K (sets1-8)
  manufacturer: Laboratoryof Molecular Medicine, Instutute of Medical Science, the
    University of Tokyo
  distribution: non-commercial
  accession: GPL4747
  technology: spotted DNA/cDNA
citation: Tamura K, Furihata M, Tsunoda T, Ashida S et al. Molecular features of hormone-refractory
  prostate cancer cells by genome-wide gene expression profiles. Cancer Res 2007 Jun
  1;67(11):5117-25.
size:
  'n': 35
  comments: n=35 samples from HRPC patients
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE6811

```
