### ISSUE TITLE
Data - GSE6099 - Tomlins, Chinnaiyan 2007

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#8]
Source: GEO
 
```yaml
label: Tomlins, Chinnaiyan 2007
accession: GSE6099
pubmed_id: 17173048
platform:
- name: Chinnaiyan Human 20K Hs6
  distribution: non-commercial
  accession: GPL2013
  technology: spotted DNA/cDNA
citation: Tomlins SA, Mehra R, Rhodes DR, Cao X et al. Integrative molecular concept
  modeling of prostate cancer progression. Nat Genet 2007 Jan;39(1):41-51.
size:
  'n': 104
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE6099

```
