### ISSUE TITLE
Data - GSE5132 - True, Nelson 2006

### ISSUE THREAD

**Issue by gadenbuie** [GerkeLab/curatedProstateData#9]
Source: GEO
 
```yaml
label: True, Nelson 2006
accession: GSE5132
pubmed_id: 16829574
platform:
- name: "FHCRC Human Prostate PEDB cDNA Array v4"
  manufacturer: FHCRC Array Facility
  distribution: non-commercial
  accession: GPL3834
  technology: spotted DNA/cDNA
- name: FHCRC Human Prostate PEDB cDNA Array v3
  manufacturer: FHCRC Array Facility
  distribution: non-commercial
  accession: GPL3836
  technology: spotted DNA/cDNA
citation: True L, Coleman I, Hawley S, Huang CY et al. A molecular correlate to the
  Gleason grading system for prostate adenocarcinoma. Proc Natl Acad Sci U S A 2006
  Jul 18;103(29):10991-6.
size:
  'n': 32
link:
  primary: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE5132

```
